# Document:
# http://simiki.org/docs/configuration.html

url: https://yi-Xu-0100.github.io/wiki
title: wiki
keywords: wiki
description: Personal wiki.
author: yi_Xu

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

default_ext: "markdown"
pygments: true
debug: false
index: true
