# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.yixuju.cn/
title: Wiki · yi_Xu
keywords: wiki;
description: Personal wiki.
author: yi_Xu

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

default_ext: md
pygments: true
debug: true

deploy:
  - type: git
    remote: origin
    branch: gh-pages
